#ifndef TIM0_CONFIG_H_
#define TIM0_CONFIG_H_

#define TIM0_MODE CTC
/* Options
1- NORMAL
2- PWM_PHASE_CORRECT
3- CTC
4- FAST_PWM */

#define TIM0_OC0_MODE TOGGLE_OC0
/* Options in non-PWM Mode
1- OC0_DISCONNECTED
2- TOGGLE_OC0
3- CLEAR_OC0
4- SET_OC0

Options in Fast PWM Mode
1- OC0_DISCONNECTED
2- NIN_INVERTING
3- INVERTING */

#define TIM0_CLOCK_SOURCE PRESCALER_1
/* Options
1- PRESCALER_1
2- PRESCALER_8
3- PRESCALER_64
4- PRESCALER_256
5- PRESCALER_1024
6- EXTERNAL_CLOCK_ON_FALLING_EDGE
7- EXTERNAL_CLOCK_ON_RISING_EDGE */

#define TIM0_INT_STATUS TIM0_INT_DISABLE
/* Options
1- Disable
2- Enable */

#define TIM0_INT_SOURCE TIM0_OVF_INT
/* Options
1- TIM0_OVF_INT
2- TIM0_CTC_INT */

#endif